/**
 * renderer3d-shaders.js — GLSL for Three.js elevation/hologram renderer
 * Single unified shader with uRenderMode (matches original WebGL renderer exactly)
 */
window.R3D_SHADERS = (function() {
  'use strict';

  // Vertex shader — uses aGrid (vec2 0-1) as both position and UV
  // Three.js ShaderMaterial provides: modelViewMatrix, projectionMatrix
  // We use 'uv' attribute (built-in) as grid coordinates
  var vertexShader = [
    'uniform sampler2D uDepth;',
    'uniform float uElevation;',
    'uniform float uElevOverride;',
    'uniform float uGapOffset;',
    '',
    'varying float vDepth;',
    'varying vec2 vUV;',
    '',
    'void main() {',
    '  vec4 d = texture2D(uDepth, uv);',
    '  float depth = d.r;',
    '  vDepth = depth;',
    '  vUV = uv;',
    '',
    '  float x = (uv.x - 0.5) * 2.0;',
    '  float z = (uv.y - 0.5) * 2.0;',
    '  float elev = uElevOverride >= -99.0 ? uElevOverride : uElevation;',
    '  float y = -depth * elev + uGapOffset;',
    '',
    '  vec4 mvPos = modelViewMatrix * vec4(x, y, z, 1.0);',
    '  gl_Position = projectionMatrix * mvPos;',
    '  gl_PointSize = 4.0 + depth * 4.0;',
    '}'
  ].join('\n');

  // Fragment shader — unified with uRenderMode
  // Mode 0: grid wireframe
  // Mode 1: source image texture
  // Mode 2: hologram body
  // Mode 3: points (circles)
  var fragmentShader = [
    'precision mediump float;',
    '',
    'varying float vDepth;',
    'varying vec2 vUV;',
    '',
    'uniform vec3 uGridColor;',
    'uniform vec3 uGridColor2;',
    'uniform vec3 uBgColor;',
    'uniform float uGlowPass;',
    'uniform float uGlow;',
    'uniform float uRenderMode;',
    'uniform sampler2D uSrcTex;',
    'uniform vec3 uHoloColor;',
    'uniform vec3 uHoloColorMid;',
    'uniform vec3 uSrcTint;',
    'uniform float uSrcTintAmt;',
    'uniform float uDither;',
    'uniform float uDitherStyle;',
    'uniform float uScanLines;',
    'uniform float uScanDensity;',
    'uniform float uScanOpacity;',
    'uniform float uScanSpeed;',
    'uniform float uScanDir;',
    'uniform float uTime;',
    '',
    'float hash(float n) { return fract(sin(n) * 43758.5453); }',
    'float hash2(vec2 p) { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }',
    '',
    'float animScanLine(float depth, float density, float speed, float time) {',
    '  float pulse = mod(time * speed, 1.0);',
    '  float d = uScanDir > 0.0 ? depth : 1.0 - depth;',
    '  float depthPhase = d * 40.0 / density;',
    '  float contour = mod(depthPhase - pulse * 40.0 / density, 1.0);',
    '  float line = smoothstep(0.4, 0.5, contour) * (1.0 - smoothstep(0.5, 0.6, contour));',
    '  return line * (0.5 + 0.5 * d);',
    '}',
    '',
    'void main() {',
    '',
    '  // Mode 1: source image',
    '  if (uRenderMode > 0.5 && uRenderMode < 1.5) {',
    '    vec3 c = texture2D(uSrcTex, vUV).rgb;',
    '    if (uScanLines > 0.5) {',
    '      float sl = animScanLine(vDepth, uScanDensity, uScanSpeed, uTime);',
    '      c *= 1.0 - sl * uScanOpacity;',
    '    }',
    '    gl_FragColor = vec4(c, 1.0);',
    '    return;',
    '  }',
    '',
    '  // Mode 2: hologram body',
    '  if (uRenderMode > 1.5 && uRenderMode < 2.5) {',
    '    vec2 uv = vUV;',
    '    float glitchLine = floor(vDepth * 200.0 + gl_FragCoord.x * 0.1);',
    '    float glitchRand = hash(glitchLine + floor(uTime * 8.0));',
    '    if (glitchRand > 0.97) {',
    '      uv.x += (hash(glitchLine * 7.0 + uTime) - 0.5) * 0.08 * vDepth;',
    '    }',
    '    vec3 img = texture2D(uSrcTex, uv).rgb;',
    '    float luma = dot(img, vec3(0.299, 0.587, 0.114));',
    '    vec3 depthColor = vDepth < 0.5',
    '      ? mix(uGridColor2, uHoloColorMid, vDepth * 2.0)',
    '      : mix(uHoloColorMid, uHoloColor, (vDepth - 0.5) * 2.0);',
    '    vec3 srcTint = img * uSrcTint * uSrcTintAmt;',
    '    vec3 tinted = depthColor * (0.2 + 0.8 * luma) * (0.4 + 0.6 * vDepth) + srcTint;',
    '    if (glitchRand > 0.97) {',
    '      float rShift = texture2D(uSrcTex, uv + vec2(0.01 * vDepth, 0.0)).r;',
    '      float bShift = texture2D(uSrcTex, uv - vec2(0.01 * vDepth, 0.0)).b;',
    '      tinted.r = uHoloColor.r * (0.2 + 0.8 * rShift) * (0.4 + 0.6 * vDepth);',
    '      tinted.b = uHoloColor.b * (0.2 + 0.8 * bShift) * (0.4 + 0.6 * vDepth);',
    '    }',
    '    if (uDither > 0.5) {',
    '      float ditherMask = 1.0;',
    '      float l = luma * 0.8 + 0.1;',
    '      if (uDitherStyle < 1.5) {',
    '        float px = floor(mod(gl_FragCoord.x / 2.0, 4.0));',
    '        float py = floor(mod(gl_FragCoord.y / 2.0, 4.0));',
    '        float idx = py * 4.0 + px;',
    '        float t = 0.0;',
    '        if (idx<0.5) t=0.0; else if (idx<1.5) t=8.0; else if (idx<2.5) t=2.0; else if (idx<3.5) t=10.0;',
    '        else if (idx<4.5) t=12.0; else if (idx<5.5) t=4.0; else if (idx<6.5) t=14.0; else if (idx<7.5) t=6.0;',
    '        else if (idx<8.5) t=3.0; else if (idx<9.5) t=11.0; else if (idx<10.5) t=1.0; else if (idx<11.5) t=9.0;',
    '        else if (idx<12.5) t=15.0; else if (idx<13.5) t=7.0; else if (idx<14.5) t=13.0; else t=5.0;',
    '        ditherMask = step(t / 16.0, l);',
    '      } else if (uDitherStyle < 2.5) {',
    '        float px = floor(mod(gl_FragCoord.x, 8.0));',
    '        float py = floor(mod(gl_FragCoord.y, 8.0));',
    '        float noise = hash2(vec2(px, py) + 0.5);',
    '        ditherMask = step(noise * 0.8, l);',
    '      } else if (uDitherStyle < 3.5) {',
    '        vec2 cell = fract(gl_FragCoord.xy / 4.0) - 0.5;',
    '        ditherMask = step(length(cell), l * 0.7);',
    '      } else if (uDitherStyle < 4.5) {',
    '        float line1 = mod(gl_FragCoord.x + gl_FragCoord.y, 6.0);',
    '        float line2 = mod(gl_FragCoord.x - gl_FragCoord.y, 6.0);',
    '        float h = max(step(1.0, line1) * step(l, 0.75), step(1.0, line2) * step(l, 0.5));',
    '        ditherMask = 1.0 - h * 0.6;',
    '      } else {',
    '        ditherMask = step(hash2(gl_FragCoord.xy + uTime * 37.0), l);',
    '      }',
    '      tinted *= 0.3 + 0.7 * ditherMask;',
    '    }',
    '    if (uScanLines > 0.5) {',
    '      float sl = animScanLine(vDepth, uScanDensity, uScanSpeed, uTime);',
    '      tinted *= 1.0 - sl * uScanOpacity;',
    '    }',
    '    float sweepPhase = mod(uTime * 0.3, 1.4) - 0.2;',
    '    float sweepDist = abs(vDepth - sweepPhase);',
    '    tinted += uHoloColor * smoothstep(0.15, 0.0, sweepDist) * 0.35;',
    '    tinted += (hash2(gl_FragCoord.xy + uTime * 100.0) - 0.5) * 0.06;',
    '    gl_FragColor = vec4(tinted, 1.0);',
    '    return;',
    '  }',
    '',
    '  // Mode 3: points (circles)',
    '  if (uRenderMode > 2.5 && uRenderMode < 3.5) {',
    '    vec2 pc = gl_PointCoord - 0.5;',
    '    if (dot(pc, pc) > 0.25) discard;',
    '    vec3 ptColor = vDepth < 0.5',
    '      ? mix(uGridColor2, uHoloColorMid, vDepth * 2.0)',
    '      : mix(uHoloColorMid, uGridColor, (vDepth - 0.5) * 2.0);',
    '    gl_FragColor = vec4(ptColor * (0.5 + 0.5 * vDepth), 1.0);',
    '    return;',
    '  }',
    '',
    '  // Mode 0: grid wireframe',
    '  vec3 gradColor = vDepth < 0.5',
    '    ? mix(uGridColor2, uHoloColorMid, vDepth * 2.0)',
    '    : mix(uHoloColorMid, uGridColor, (vDepth - 0.5) * 2.0);',
    '  float bright = 0.3 + 0.7 * vDepth;',
    '  if (uScanLines > 0.5) {',
    '    float sl = animScanLine(vDepth, uScanDensity, uScanSpeed, uTime);',
    '    bright *= 1.0 - sl * uScanOpacity;',
    '  }',
    '  if (uGlowPass > 0.5) {',
    '    gl_FragColor = vec4(gradColor * uGlow * 0.3, 1.0);',
    '  } else {',
    '    gl_FragColor = vec4(gradColor * bright, 1.0);',
    '  }',
    '}'
  ].join('\n');

  return { vertexShader: vertexShader, fragmentShader: fragmentShader };
})();
