/**
 * renderer3d-shaders.js — GLSL shader sources for Three.js elevation/hologram renderer
 * Used by renderer3d.js via window.R3D_SHADERS
 */
window.R3D_SHADERS = (function() {
  'use strict';

  // ── Shared vertex shader (all layers use depth displacement) ──
  var meshVert = [
    'uniform sampler2D uDepth;',
    'uniform float uElevation;',
    'uniform float uElevOverride;',
    'uniform float uGapOffset;',
    '',
    'varying float vDepth;',
    'varying vec2 vUV;',
    'varying vec2 vScreen;',
    '',
    'void main() {',
    '  vec4 d = texture2D(uDepth, uv);',
    '  float depth = d.r;',
    '  vDepth = depth;',
    '  vUV = uv;',
    '',
    '  vec3 pos = position;',
    '  float elev = uElevOverride >= -99.0 ? uElevOverride : uElevation;',
    '  pos.y = -depth * elev + uGapOffset;',
    '',
    '  vec4 mvPos = modelViewMatrix * vec4(pos, 1.0);',
    '  gl_Position = projectionMatrix * mvPos;',
    '  vScreen = gl_Position.xy * 0.5 + 0.5;',
    '  gl_PointSize = 4.0 + depth * 4.0;',
    '}'
  ].join('\n');

  // ── Grid fragment shader (wireframe + glow) ──
  var gridFrag = [
    'precision mediump float;',
    '',
    'varying float vDepth;',
    'varying vec2 vUV;',
    '',
    'uniform vec3 uGridColor;',
    'uniform vec3 uGridColor2;',
    'uniform vec3 uHoloColorMid;',
    'uniform float uGlowPass;',
    'uniform float uGlow;',
    'uniform float uScanLines;',
    'uniform float uScanDensity;',
    'uniform float uScanOpacity;',
    'uniform float uScanSpeed;',
    'uniform float uScanDir;',
    'uniform float uTime;',
    '',
    'float animScanLine(float depth, float density, float speed, float time) {',
    '  float pulse = mod(time * speed, 1.0);',
    '  float d = uScanDir > 0.0 ? depth : 1.0 - depth;',
    '  float depthPhase = d * 40.0 / density;',
    '  float contour = mod(depthPhase - pulse * 40.0 / density, 1.0);',
    '  float line = smoothstep(0.4, 0.5, contour) * (1.0 - smoothstep(0.5, 0.6, contour));',
    '  return line * (0.5 + 0.5 * d);',
    '}',
    '',
    'void main() {',
    '  vec3 gradColor = vDepth < 0.5',
    '    ? mix(uGridColor2, uHoloColorMid, vDepth * 2.0)',
    '    : mix(uHoloColorMid, uGridColor, (vDepth - 0.5) * 2.0);',
    '  float bright = 0.3 + 0.7 * vDepth;',
    '',
    '  if (uScanLines > 0.5) {',
    '    float sl = animScanLine(vDepth, uScanDensity, uScanSpeed, uTime);',
    '    bright *= 1.0 - sl * uScanOpacity;',
    '  }',
    '',
    '  if (uGlowPass > 0.5) {',
    '    gl_FragColor = vec4(gradColor * uGlow * 0.3, 1.0);',
    '  } else {',
    '    gl_FragColor = vec4(gradColor * bright, 1.0);',
    '  }',
    '}'
  ].join('\n');

  // ── Points fragment shader (dot/dotmatrix grid) ──
  var pointsFrag = [
    'precision mediump float;',
    '',
    'varying float vDepth;',
    '',
    'uniform vec3 uGridColor;',
    'uniform vec3 uGridColor2;',
    'uniform vec3 uHoloColorMid;',
    '',
    'void main() {',
    '  vec2 pc = gl_PointCoord - 0.5;',
    '  if (dot(pc, pc) > 0.25) discard;',
    '  vec3 ptColor = vDepth < 0.5',
    '    ? mix(uGridColor2, uHoloColorMid, vDepth * 2.0)',
    '    : mix(uHoloColorMid, uGridColor, (vDepth - 0.5) * 2.0);',
    '  gl_FragColor = vec4(ptColor * (0.5 + 0.5 * vDepth), 1.0);',
    '}'
  ].join('\n');

  // ── Source image fragment shader (plain textured mesh) ──
  var sourceFrag = [
    'precision mediump float;',
    '',
    'varying float vDepth;',
    'varying vec2 vUV;',
    '',
    'uniform sampler2D uSrcTex;',
    'uniform float uScanLines;',
    'uniform float uScanDensity;',
    'uniform float uScanOpacity;',
    'uniform float uScanSpeed;',
    'uniform float uScanDir;',
    'uniform float uTime;',
    '',
    'float animScanLine(float depth, float density, float speed, float time) {',
    '  float pulse = mod(time * speed, 1.0);',
    '  float d = uScanDir > 0.0 ? depth : 1.0 - depth;',
    '  float depthPhase = d * 40.0 / density;',
    '  float contour = mod(depthPhase - pulse * 40.0 / density, 1.0);',
    '  float line = smoothstep(0.4, 0.5, contour) * (1.0 - smoothstep(0.5, 0.6, contour));',
    '  return line * (0.5 + 0.5 * d);',
    '}',
    '',
    'void main() {',
    '  vec3 c = texture2D(uSrcTex, vUV).rgb;',
    '  if (uScanLines > 0.5) {',
    '    float sl = animScanLine(vDepth, uScanDensity, uScanSpeed, uTime);',
    '    c *= 1.0 - sl * uScanOpacity;',
    '  }',
    '  gl_FragColor = vec4(c, 1.0);',
    '}'
  ].join('\n');

  // ── Hologram fragment shader (full hologram body rendering) ──
  var holoFrag = [
    'precision mediump float;',
    '',
    'varying float vDepth;',
    'varying vec2 vUV;',
    '',
    'uniform sampler2D uSrcTex;',
    'uniform vec3 uHoloColor;',
    'uniform vec3 uHoloColorMid;',
    'uniform vec3 uGridColor2;',
    'uniform vec3 uSrcTint;',
    'uniform float uSrcTintAmt;',
    'uniform float uDither;',
    'uniform float uDitherStyle;', // 0=none,1=bayer4,2=bayer8,3=halftone,4=crosshatch,5=noise
    'uniform float uScanLines;',
    'uniform float uScanDensity;',
    'uniform float uScanOpacity;',
    'uniform float uScanSpeed;',
    'uniform float uScanDir;',
    'uniform float uTime;',
    '',
    'float hash(float n) { return fract(sin(n) * 43758.5453); }',
    'float hash2(vec2 p) { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }',
    '',
    'float animScanLine(float depth, float density, float speed, float time) {',
    '  float pulse = mod(time * speed, 1.0);',
    '  float d = uScanDir > 0.0 ? depth : 1.0 - depth;',
    '  float depthPhase = d * 40.0 / density;',
    '  float contour = mod(depthPhase - pulse * 40.0 / density, 1.0);',
    '  float line = smoothstep(0.4, 0.5, contour) * (1.0 - smoothstep(0.5, 0.6, contour));',
    '  return line * (0.5 + 0.5 * d);',
    '}',
    '',
    'void main() {',
    '  vec2 uv = vUV;',
    '',
    '  // Glitch displacement',
    '  float glitchLine = floor(vDepth * 200.0 + gl_FragCoord.x * 0.1);',
    '  float glitchRand = hash(glitchLine + floor(uTime * 8.0));',
    '  if (glitchRand > 0.97) {',
    '    uv.x += (hash(glitchLine * 7.0 + uTime) - 0.5) * 0.08 * vDepth;',
    '  }',
    '',
    '  vec3 img = texture2D(uSrcTex, uv).rgb;',
    '  float luma = dot(img, vec3(0.299, 0.587, 0.114));',
    '',
    '  // 3-stop depth gradient',
    '  vec3 depthColor = vDepth < 0.5',
    '    ? mix(uGridColor2, uHoloColorMid, vDepth * 2.0)',
    '    : mix(uHoloColorMid, uHoloColor, (vDepth - 0.5) * 2.0);',
    '',
    '  vec3 srcTint = img * uSrcTint * uSrcTintAmt;',
    '  vec3 tinted = depthColor * (0.2 + 0.8 * luma) * (0.4 + 0.6 * vDepth) + srcTint;',
    '',
    '  // Chromatic aberration on glitch lines',
    '  if (glitchRand > 0.97) {',
    '    float rShift = texture2D(uSrcTex, uv + vec2(0.01 * vDepth, 0.0)).r;',
    '    float bShift = texture2D(uSrcTex, uv - vec2(0.01 * vDepth, 0.0)).b;',
    '    tinted.r = uHoloColor.r * (0.2 + 0.8 * rShift) * (0.4 + 0.6 * vDepth);',
    '    tinted.b = uHoloColor.b * (0.2 + 0.8 * bShift) * (0.4 + 0.6 * vDepth);',
    '  }',
    '',
    '  // Dither styles: 1=bayer4, 2=bayer8, 3=halftone, 4=crosshatch, 5=noise',
    '  if (uDither > 0.5) {',
    '    float ditherMask = 1.0;',
    '    float l = luma * 0.8 + 0.1;',
    '',
    '    if (uDitherStyle < 1.5) {',
    '      // Bayer 4x4',
    '      float px = floor(mod(gl_FragCoord.x / 2.0, 4.0));',
    '      float py = floor(mod(gl_FragCoord.y / 2.0, 4.0));',
    '      float idx = py * 4.0 + px;',
    '      float t = 0.0;',
    '      if (idx<0.5) t=0.0; else if (idx<1.5) t=8.0; else if (idx<2.5) t=2.0; else if (idx<3.5) t=10.0;',
    '      else if (idx<4.5) t=12.0; else if (idx<5.5) t=4.0; else if (idx<6.5) t=14.0; else if (idx<7.5) t=6.0;',
    '      else if (idx<8.5) t=3.0; else if (idx<9.5) t=11.0; else if (idx<10.5) t=1.0; else if (idx<11.5) t=9.0;',
    '      else if (idx<12.5) t=15.0; else if (idx<13.5) t=7.0; else if (idx<14.5) t=13.0; else t=5.0;',
    '      ditherMask = step(t / 16.0, l);',
    '',
    '    } else if (uDitherStyle < 2.5) {',
    '      // Bayer 8x8 (approximated with 4x4 + sub-pixel offset)',
    '      float px = floor(mod(gl_FragCoord.x, 8.0));',
    '      float py = floor(mod(gl_FragCoord.y, 8.0));',
    '      float t4x = floor(mod(px, 4.0));',
    '      float t4y = floor(mod(py, 4.0));',
    '      float idx = t4y * 4.0 + t4x;',
    '      float t = 0.0;',
    '      if (idx<0.5) t=0.0; else if (idx<1.5) t=32.0; else if (idx<2.5) t=8.0; else if (idx<3.5) t=40.0;',
    '      else if (idx<4.5) t=48.0; else if (idx<5.5) t=16.0; else if (idx<6.5) t=56.0; else if (idx<7.5) t=24.0;',
    '      else if (idx<8.5) t=12.0; else if (idx<9.5) t=44.0; else if (idx<10.5) t=4.0; else if (idx<11.5) t=36.0;',
    '      else if (idx<12.5) t=60.0; else if (idx<13.5) t=28.0; else if (idx<14.5) t=52.0; else t=20.0;',
    '      float sub = (px >= 4.0 ? 2.0 : 0.0) + (py >= 4.0 ? 1.0 : 0.0);',
    '      t = t + sub;',
    '      ditherMask = step(t / 64.0, l);',
    '',
    '    } else if (uDitherStyle < 3.5) {',
    '      // Halftone (circular dots)',
    '      vec2 cell = floor(gl_FragCoord.xy / 4.0);',
    '      vec2 offset = fract(gl_FragCoord.xy / 4.0) - 0.5;',
    '      float dist = length(offset);',
    '      float radius = l * 0.7;',
    '      ditherMask = step(dist, radius);',
    '',
    '    } else if (uDitherStyle < 4.5) {',
    '      // Crosshatch',
    '      float line1 = mod(gl_FragCoord.x + gl_FragCoord.y, 6.0);',
    '      float line2 = mod(gl_FragCoord.x - gl_FragCoord.y, 6.0);',
    '      float h1 = step(1.0, line1) * step(l, 0.75);',
    '      float h2 = step(1.0, line2) * step(l, 0.5);',
    '      float h3 = step(2.0, line1) * step(l, 0.25);',
    '      ditherMask = 1.0 - max(max(h1, h2), h3) * 0.6;',
    '',
    '    } else {',
    '      // Noise dither',
    '      float noise = hash2(gl_FragCoord.xy + uTime * 37.0);',
    '      ditherMask = step(noise, l);',
    '    }',
    '',
    '    tinted *= 0.3 + 0.7 * ditherMask;',
    '  }',
    '',
    '  // Scan lines',
    '  if (uScanLines > 0.5) {',
    '    float sl = animScanLine(vDepth, uScanDensity, uScanSpeed, uTime);',
    '    tinted *= 1.0 - sl * uScanOpacity;',
    '  }',
    '',
    '  // CRT sweep',
    '  float sweepPhase = mod(uTime * 0.3, 1.4) - 0.2;',
    '  float sweepDist = abs(vDepth - sweepPhase);',
    '  float sweep = smoothstep(0.15, 0.0, sweepDist) * 0.35;',
    '  tinted += uHoloColor * sweep;',
    '',
    '  // Film grain',
    '  float grain = (hash2(gl_FragCoord.xy + uTime * 100.0) - 0.5) * 0.06;',
    '  tinted += grain;',
    '',
    '  gl_FragColor = vec4(tinted, 1.0);',
    '}'
  ].join('\n');

  // ── Depth colorization fragment shader ──
  var depthFrag = [
    'precision mediump float;',
    '',
    'varying float vDepth;',
    '',
    'uniform vec3 uGridColor;',
    'uniform vec3 uGridColor2;',
    'uniform vec3 uHoloColorMid;',
    '',
    'void main() {',
    '  vec3 c = vDepth < 0.5',
    '    ? mix(uGridColor2, uHoloColorMid, vDepth * 2.0)',
    '    : mix(uHoloColorMid, uGridColor, (vDepth - 0.5) * 2.0);',
    '  gl_FragColor = vec4(c * (0.3 + 0.7 * vDepth), 1.0);',
    '}'
  ].join('\n');

  // ── Post-processing: Scan line pass ──
  var scanLineShader = {
    uniforms: {
      tDiffuse: { value: null },
      uScanDensity: { value: 3.0 },
      uScanOpacity: { value: 0.3 },
      uTime: { value: 0.0 }
    },
    vertexShader: [
      'varying vec2 vUv;',
      'void main() {',
      '  vUv = uv;',
      '  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);',
      '}'
    ].join('\n'),
    fragmentShader: [
      'precision mediump float;',
      'uniform sampler2D tDiffuse;',
      'uniform float uScanDensity;',
      'uniform float uScanOpacity;',
      'uniform float uTime;',
      'varying vec2 vUv;',
      'void main() {',
      '  vec4 c = texture2D(tDiffuse, vUv);',
      '  float line = sin(gl_FragCoord.y * uScanDensity + uTime * 2.0) * 0.5 + 0.5;',
      '  c.rgb *= 1.0 - line * uScanOpacity;',
      '  gl_FragColor = c;',
      '}'
    ].join('\n')
  };

  // ── Post-processing: Vignette pass ──
  var vignetteShader = {
    uniforms: {
      tDiffuse: { value: null },
      uStrength: { value: 0.0 }
    },
    vertexShader: [
      'varying vec2 vUv;',
      'void main() { vUv = uv; gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0); }'
    ].join('\n'),
    fragmentShader: [
      'precision mediump float;',
      'uniform sampler2D tDiffuse;',
      'uniform float uStrength;',
      'varying vec2 vUv;',
      'void main() {',
      '  vec4 c = texture2D(tDiffuse, vUv);',
      '  float d = distance(vUv, vec2(0.5));',
      '  c.rgb *= 1.0 - smoothstep(0.3, 0.8, d) * uStrength;',
      '  gl_FragColor = c;',
      '}'
    ].join('\n')
  };

  return {
    meshVert: meshVert,
    gridFrag: gridFrag,
    pointsFrag: pointsFrag,
    sourceFrag: sourceFrag,
    holoFrag: holoFrag,
    depthFrag: depthFrag,
    scanLineShader: scanLineShader,
    vignetteShader: vignetteShader
  };
})();
